#!/usr/bin/env node

/**
 * Setup Environment Configuration
 * 
 * This script reads from .env file and generates env-config.js
 * It can be run manually or as part of a build process
 * 
 * Usage:
 *   node setup-env.js
 * 
 * Or add to package.json scripts:
 *   "setup:env": "node setup-env.js"
 */

const fs = require('fs');
const path = require('path');

// Read the .env file
const envPath = path.join(__dirname, '.env');

try {
    const envContent = fs.readFileSync(envPath, 'utf-8');
    
    // Parse .env file
    const envVars = {};
    envContent.split('\n').forEach(line => {
        const trimmed = line.trim();
        // Skip comments and empty lines
        if (!trimmed || trimmed.startsWith('#')) return;
        
        const [key, ...valueParts] = trimmed.split('=');
        const value = valueParts.join('=').trim();
        envVars[key.trim()] = value;
    });
    
    // Extract the values we need (prioritize API_BASE_URL over FRONTEND_API_URL)
    const apiUrl = envVars.API_BASE_URL || envVars.FRONTEND_API_URL || 'http://localhost:8000/api/v1';
    const calendarName = envVars.CALENDAR_NAME || 'My Timetable';
    const timezone = envVars.TIMEZONE || 'UTC';
    
    // Generate the env-config.js content
    const configContent = `// Auto-generated environment configuration
// This file is generated by setup-env.js
// Do not commit to version control

window.ENV_API_BASE_URL = '${apiUrl}';
window.ENV_CALENDAR_NAME = '${calendarName}';
window.ENV_TIMEZONE = '${timezone}';
`;
    
    // Write to env-config.js
    const configPath = path.join(__dirname, 'env-config.js');
    fs.writeFileSync(configPath, configContent, 'utf-8');
    
    console.log('✓ env-config.js generated successfully!');
    console.log(`  API Base URL: ${apiUrl}`);
    console.log(`  Calendar Name: ${calendarName}`);
    console.log(`  Timezone: ${timezone}`);
} catch (error) {
    console.error('✗ Error generating env-config.js:', error.message);
    process.exit(1);
}
 