#!/usr/bin/env node

/**
 * Watch Environment Configuration
 * 
 * This script watches for changes to .env and automatically regenerates env-config.js
 * 
 * Usage:
 *   node watch-env.js
 * 
 * Or add to package.json scripts:
 *   "watch:env": "node watch-env.js"
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const configPath = path.join(__dirname, 'env-config.js');

function generateConfig() {
    try {
        const envContent = fs.readFileSync(envPath, 'utf-8');
        
        // Parse .env file
        const envVars = {};
        envContent.split('\n').forEach(line => {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#')) return;
            
            const [key, ...valueParts] = trimmed.split('=');
            const value = valueParts.join('=').trim();
            envVars[key.trim()] = value;
        });
        
        // Extract the values we need
        const apiUrl = envVars.API_BASE_URL || envVars.FRONTEND_API_URL || 'http://localhost:8000/api/v1';
        const calendarName = envVars.CALENDAR_NAME || 'My Timetable';
        const timezone = envVars.TIMEZONE || 'UTC';
        
        // Generate the env-config.js content
        const configContent = `// Auto-generated environment configuration
// This file is generated by watch-env.js
// Do not commit to version control

window.ENV_API_BASE_URL = '${apiUrl}';
window.ENV_CALENDAR_NAME = '${calendarName}';
window.ENV_TIMEZONE = '${timezone}';
`;
        
        fs.writeFileSync(configPath, configContent, 'utf-8');
        console.log(`[${new Date().toLocaleTimeString()}] ✓ env-config.js updated`);
    } catch (error) {
        console.error(`[${new Date().toLocaleTimeString()}] ✗ Error:`, error.message);
    }
}

// Initial generation
generateConfig();

// Watch for changes to .env
fs.watch(envPath, (eventType) => {
    if (eventType === 'change') {
        generateConfig();
    }
});

console.log('👀 Watching .env for changes... (Press Ctrl+C to stop)');
